# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 末影随想
email: moycatus@gmail.com
description: >-
  沙上并禽池上暝 云破月来花弄影
keyword: >-
  moycat, blog, 博客, 随想
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  moycat
timezone: Asia/Shanghai

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2017

# Author
author: 'Moycat'
bio: 'You''ll always be luck if you know how to make friends with strange cats.'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: false

# Comments
disqus: false
disqus_url: 'https://liaokeyu.disqus.com/embed.js'

livere: false
livere_uid: MTAyMC8yODEwMC80Njcz

# Reward 赞赏功能 by Ray-Eldath
reward:
  enable: false
  reward_comment: '真诚赞赏 手有余香'
  wechatpay: 'http://ray-eldath.image.alimmdn.com/basic/wechatpay.jpg'
  alipay: 'http://ray-eldath.image.alimmdn.com/basic/alipay.jpg'

# b2t 回到顶部 by Ray-Eldath
b2t: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# Theme Color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: 'mailto:moycatus@gmail.com'
  github: '//github.com/moycat'
  instagram: '//www.instagram.com/moycatus'
  zhihu: '//www.zhihu.com/people/moycat'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md', '.idea']

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-paginate

# Deployment
host: 0.0.0.0
